/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { OwnableInterface } from "./OwnableInterface";
export type { VRFCoordinatorV2Interface } from "./VRFCoordinatorV2Interface";
